### ISSUE TITLE
1.15.0 Causes errors on dev server

### ISSUE THREAD

**Issue by shekibobo** [flyerhzm/rails_best_practices#203]
Using with ActiveAdmin. When starting the server after upgrading to 1.15.0, I get the error:

```
~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/namespace.rb:217:in `eval': undefined method `[]' for nil:NilClass (NoMethodError)
  from ~/.rvm/gems/ruby-2.1.0/gems/inherited_resources-1.4.1/lib/inherited_resources/url_helpers.rb:67:in `each'
  from ~/.rvm/gems/ruby-2.1.0/gems/inherited_resources-1.4.1/lib/inherited_resources/url_helpers.rb:67:in `create_resources_url_helpers!'
  from ~/.rvm/gems/ruby-2.1.0/gems/inherited_resources-1.4.1/lib/inherited_resources/class_methods.rb:373:in `inherited'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/resource_controller.rb:37:in `inherited'
  from (eval):1:in `register_resource_controller'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/namespace.rb:217:in `eval'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/namespace.rb:217:in `register_resource_controller'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/namespace.rb:47:in `register'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:120:in `register'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin.rb:76:in `register'
  from ~/my_app/app/admin/customer_asset.rb:1:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:179:in `load'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:171:in `block in load!'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:171:in `each'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:171:in `load!'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:195:in `routes'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin.rb:80:in `routes'
  from ~/my_app/config/routes.rb:2:in `block in <top (required)>'
  from ~/.rvm/gems/ruby-2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:341:in `instance_exec'
  from ~/.rvm/gems/ruby-2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:341:in `eval_block'
  from ~/.rvm/gems/ruby-2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:319:in `draw'
  from ~/my_app/config/routes.rb:1:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `each'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:16:in `reload!'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application.rb:102:in `reload_routes!'
  from ~/.rvm/gems/ruby-2.1.0/bundler/gems/active_admin-6f04ed5cec24/lib/active_admin/application.rb:245:in `block in attach_reloader'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:387:in `_run__1625301191216833404__prepare__callbacks'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
  from ~/.rvm/gems/ruby-2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
  from ~/.rvm/gems/ruby-2.1.0/gems/actionpack-4.0.2/lib/action_dispatch/middleware/reloader.rb:46:in `prepare!'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `run'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `call'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
  from ~/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/application.rb:215:in `initialize!'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
  from ~/my_app/config/environment.rb:5:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `block in require'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
  from ~/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require'
  from ~/my_app/config.ru:3:in `block in <main>'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  from ~/my_app/config.ru:in `new'
  from ~/my_app/config.ru:in `<main>'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/server.rb:277:in `build_app_and_options_from_config'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/server.rb:199:in `app'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/server.rb:48:in `app'
  from ~/.rvm/gems/ruby-2.1.0/gems/rack-1.5.2/lib/rack/server.rb:314:in `wrapped_app'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands/server.rb:75:in `start'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:76:in `block in <top (required)>'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:71:in `tap'
  from ~/.rvm/gems/ruby-2.1.0/gems/railties-4.0.2/lib/rails/commands.rb:71:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

Nothing else changed in the app.

Here's the line in ActiveAdmin that appears to throw the error: https://github.com/gregbell/active_admin/blob/6f04ed5cec24ce2deef14c9b6670ecf79778b777/lib/active_admin/namespace.rb#L217
